filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
  processors:
    - add_kubernetes_metadata:
        in_cluster: true
filebeat.config.modules.path: /usr/share/filebeat/modules.d

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
